name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build TinyText
        run: xcodebuild clean build -project TinyText.xcodeproj -scheme TinyText -configuration Release -derivedDataPath /tmp/tinybuild/tinytext CODE_SIGN_IDENTITY="-"
